[package]
name = "maak-ui"
version.workspace = true
edition.workspace = true

[feature]
config = ["dep:config"]

[dependencies]
gpui.workspace = true
gpui_platform.workspace = true
log.workspace = true
serde.workspace = true

smallvec = "1.15.1"
uuid = { version = "1.20.0", features = ["v4"] }
toml = "1.1"
xdg = "3.0.0"

# feature = "config"
config = { version = "0.15.22", default-features = false, features = ["toml"], optional = true }

[dev-dependencies]
anyhow.workspace = true
pretty_env_logger.workspace = true

[[example]]
name = "preview"
required-features = ["config"]
